apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sec-app-tf.fullname" . }}
  labels:
    {{- include "sec-app-tf.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "sec-app-tf.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sec-app-tf.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}