apiVersion: v1
kind: Service
metadata:
  name: {{ include "sec-app-tf.fullname" . }}
  labels:
    {{- include "sec-app-tf.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: https
  selector:
    {{- include "sec-app-tf.selectorLabels" . | nindent 4 }}
